version: '3'

services:

  forge:
    build: .
    volumes:
      - ./config/users.conf:/etc/sftp/users.conf:ro
    ports:
      - "2222:22"
      - "8080:80"
    networks:
      - coderforge-network

  mongo:
    image: "mongo:jessie"
    ports:
      - "27017:27017"
    networks:
      - coderforge-network

networks:
  coderforge-network:
    driver: bridge